fn_params_layout="Vertical"
force_multiline_blocks=true
format_code_in_doc_comments=true
imports_layout="Vertical"
imports_granularity="Item"
normalize_doc_attributes=true
struct_field_align_threshold=20
struct_lit_single_line=false
wrap_comments=true







