[book]
title = "FastClip"
description = "Specification, architecture and process for the FastClip refactor."
authors = ["wlwatkins"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
smart-punctuation = true
no-section-label = false

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 20
